### ISSUE TITLE
双击文本后不能修改内容

### ISSUE THREAD

**Issue by booksword** [Alvin-Liu/h5editor#5]
请问要怎么修改才能实现这个功能呢，我把
components/blocks/text/index.vue
里面的
    <a :style="linkStyle | calcStyle" href="#" v-html="cm.props.text"></a>
换成
    <input  :style="linkStyle | calcStyle" href="#"  v-model="cm.props.text">
后显示了输入框，但只是只读，不能编辑
cm 函数只有get方法，没有set方法，该怎么实现呢

  computed: {
    cm () {
      return this.$store.getters.getCompConfigByCompid(this.compid)
    },
    linkStyle () {
      const css = this.cm.css
      return {
        ft: css.ft
      }
    }
  }

**Comment by booksword** [comment]
找到原因了
     deselect (e) {
      if (this.$el.contains(e.target)) {
        e.preventDefault()  // 防止拖动时文字被选中
      }
这句删掉后 a标签改成input标签就可以修改了
不关 computed cm()的事

**Comment by Alvin-Liu** [comment]
@booksword 也可以在属性配置中添加一个输入框来更新，正在考虑出一个表单组件，有好的意见欢迎提供

**Comment by Alvin-Liu** [comment]
- 已添加右键删除
- 已修复文字不能修改的问题（在属性配置中修改）
