### ISSUE TITLE
你好，如果可以想问一下您的微信?

### ISSUE THREAD

**Issue by HalleyGao** [Alvin-Liu/h5editor#6]
你好，详细看了一下您的这个demo 感觉写的很棒，不知道日后还想继续做下去吗，想加您微信，详细聊一下！
我的微信，weiued2015

**Comment by Alvin-Liu** [comment]
@HalleyGao 好的，已加您，最近太忙没时间更新，许多问题还没有来得及修复，日后会继续完善
